export interface Productos {
id:number;
nombre:string;
autor:string;
paginas:number;
imagen:string;

}

export const ListaProductos:Array<Productos>=
    [{ id:1,
    nombre:"Jardin de los inocentes",
    autor:"Carlos Pinto",
    paginas:482,
    imagen:"img/producto1.jpg",
    },
    { id:2,
    nombre:"El principito",
    autor:"Antoine De Saint-Exupery",
    paginas:96,
    imagen:"img/producto2.jpg",
    },
    { id:3,
    nombre:"Frankenstein",
    autor:"Mary Shelley",
    paginas:256,
    imagen:"img/producto3.jpg",
    },
    { id:4,
     nombre:"El visitante",
     autor:"Stephen King",
     paginas:592,
     imagen:"img/producto4.jpg",
    },
    { id:5,
      nombre:"Supernova",
      autor:"Marissa Meyer",
      paginas:553,
       imagen:"img/producto5.jpg",
    },
    { id:6,
     nombre:"El Silencio de los Malditos",
     autor:"Carlos Pinto",
     paginas:380,
     imagen:"img/producto6.jpg",
    },
    { id:7,
      nombre:"Alicia a Traves del Espejo",
      autor:"Lewis Carroll",
      paginas:160,
      imagen:"img/producto7.jpg",
    },
    { id:8,
        nombre:"Cinder",
        autor:"Marissa Meyer",
        paginas:416,
        imagen:"img/producto8.jpg",
        },
     { id:9,
        nombre:"La Puerta del Bosque",
        autor:"Melissa Albert",
        paginas:416,
        imagen:"img/producto9.jpg",
        },
     { id:10,
        nombre:"Reino De Sombras",
        autor:"Sophie Jordan",
        paginas:328,
        imagen:"img/producto10.jpg",
            }
];